org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Версии: https://fabricmc.net/develop
minecraft_version=1.21.4
yarn_mappings=1.21.4+build.8
loader_version=0.16.14
fabric_api_version=0.119.2+1.21.4
fabric_kotlin_version=1.13.3+kotlin.2.1.21

mod_version=1.0.0
maven_group=dev.hotpotato
archives_base_name=hotpotato-hud
